#!/usr/bin/env python3
"""
Compatibility shim for deprecated pipeline entry `rvm_attribute_to_xml_to_cii.py`.

Deprecated behavior:
- Historical path performed RVM(+ATTR) -> REV -> XML -> CII.

Current behavior:
- Forwards to `rvm_attribute_to_xml.py` only.
- Emits deprecation warning.
- Does NOT execute XML->CII stage.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Deprecated shim. Forwards to rvm_attribute_to_xml.py (XML-only).',
        add_help=True,
    )
    parser.add_argument('--input', required=True, type=Path)
    parser.add_argument('--output', required=False, type=Path, default=None)
    parser.add_argument('--output-xml', required=False, type=Path, default=None)
    parser.add_argument('--output-cii', required=False, type=Path, default=None)
    parser.add_argument('--attributes', required=False, type=Path, default=None)
    parser.add_argument('--output-rev', required=False, type=Path, default=None)
    parser.add_argument('--rvmparser-bin', required=False, type=Path, default=None)
    parser.add_argument('--python-exe', required=False, type=Path, default=Path(sys.executable))
    parser.add_argument('--coord-factor', required=False, type=float, default=1000.0)
    parser.add_argument('--node-start', required=False, type=int, default=10)
    parser.add_argument('--node-step', required=False, type=int, default=10)
    parser.add_argument('--node-merge-tolerance', required=False, type=float, default=0.5)
    parser.add_argument('--source', required=False, type=str, default='AVEVA PSI')
    parser.add_argument('--purpose', required=False, type=str, default='Preliminary stress run')
    parser.add_argument('--title-line', required=False, type=str, default='PSI stress Output')
    parser.add_argument('--enable-psi-rigid-logic', action='store_true')
    parser.add_argument('--template-cii', required=False, type=Path, default=None)
    parser.add_argument('--coords-mode', required=False, type=str, default='first')
    return parser


def _resolve_output_xml(args: argparse.Namespace) -> Path:
    if args.output is not None:
        return args.output.resolve()
    if args.output_xml is not None:
        return args.output_xml.resolve()
    if args.output_cii is not None:
        base = args.output_cii.resolve()
        derived = base.with_suffix('.xml')
        print(
            '[DEPRECATED] --output-cii is no longer generated by this entry; '
            f'writing XML to {derived} instead.'
        )
        return derived
    raise ValueError('One of --output, --output-xml, or --output-cii must be provided.')


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    target_script = script_dir / 'rvm_attribute_to_xml.py'
    if not target_script.exists():
        raise FileNotFoundError(f'Missing forward target script: {target_script}')

    output_xml = _resolve_output_xml(args)

    print(
        '[DEPRECATED] rvm_attribute_to_xml_to_cii.py is deprecated and now forwards '\
        'to rvm_attribute_to_xml.py (XML-only). XML->CII is not performed in this entry.'
    )

    cmd: list[str] = [
        str(args.python_exe.resolve()),
        str(target_script),
        '--input', str(args.input.resolve()),
        '--output', str(output_xml),
        '--coord-factor', str(args.coord_factor),
        '--node-start', str(args.node_start),
        '--node-step', str(args.node_step),
        '--node-merge-tolerance', str(args.node_merge_tolerance),
        '--source', args.source,
        '--purpose', args.purpose,
        '--title-line', args.title_line,
    ]

    if args.attributes is not None:
        cmd.extend(['--attributes', str(args.attributes.resolve())])
    if args.output_rev is not None:
        cmd.extend(['--output-rev', str(args.output_rev.resolve())])
    if args.rvmparser_bin is not None:
        cmd.extend(['--rvmparser-bin', str(args.rvmparser_bin.resolve())])
    if args.enable_psi_rigid_logic:
        cmd.append('--enable-psi-rigid-logic')

    completed = subprocess.run(cmd, check=False)
    return int(completed.returncode)


if __name__ == '__main__':
    raise SystemExit(main())
